routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from models import db, User
import logging
import re

main = Blueprint('main', __name__)


@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        try:
            first_name = request.form['first_name']
            last_name = request.form['last_name']
            email = request.form['email']
            phone = request.form['phone']
            password = request.form['password']
            address = request.form['address']
            city = request.form['city']
            state = request.form['state']
            zip_code = request.form['zip_code']
            country = request.form['country']
            area = request.form['area']
            group = request.form['group']
            department = request.form['department']

            # Validaciones del lado del servidor
            if not first_name or not first_name.isalpha() or len(first_name) > 50:
                flash('First name is required and should only contain alphabetic characters (max 50).')
                return redirect(url_for('main.register'))

            if not last_name or not last_name.isalpha() or len(last_name) > 50:
                flash('Last name is required and should only contain alphabetic characters (max 50).')
                return redirect(url_for('main.register'))

            if User.query.filter_by(email=email).first():
                flash('Email already registered.')
                return redirect(url_for('main.register'))

            email_pattern = re.compile(r'^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$')
            if not email_pattern.match(email):
                flash('Invalid email format.')
                return redirect(url_for('main.register'))

            if User.query.filter_by(phone=phone).first():
                flash('Phone numer already registered.')
                return redirect(url_for('main.register'))

            phone_pattern = re.compile(r'^[+]+[0-9]{10,12}$')
            if not phone_pattern.match(phone):
                flash('Invalid phone format')
                return redirect(url_for('main.register'))

            password_pattern = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$')
            if not password_pattern.match(password):
                flash(
                    'Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.')
                return redirect(url_for('main.register'))

            if address and len(address) > 200:
                flash('Address should not exceed 200 characters.')
                return redirect(url_for('main.register'))

            if city and len(city) > 100:
                flash('City should not exceed 100 characters.')
                return redirect(url_for('main.register'))

            if state and len(state) > 100:
                flash('State should not exceed 100 characters.')
                return redirect(url_for('main.register'))

            if zip_code and (not zip_code.isdigit() or len(zip_code) < 5 or len(zip_code) > 10):
                flash('Zip code should contain only numeric characters (5-10 characters).')
                return redirect(url_for('main.register'))

            if country and len(country) > 100:
                flash('Country should not exceed 100 characters.')
                return redirect(url_for('main.register'))

            if not area or len(area) > 100:
                flash('Area should not exceed 100 characters.')
                return redirect(url_for('main.register'))

            if not group or len(group) > 100:
                flash('Group should not exceed 100 characters.')
                return redirect(url_for('main.register'))

            if not department or len(department) > 100:
                flash('Department should not exceed 100 characters.')
                return redirect(url_for('main.register'))

            user = User(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone=phone,
                address=address,
                city=city,
                state=state,
                zip_code=zip_code,
                country=country,
                area=area,
                group=group,
                department=department
            )
            user.set_password(password)
            db.session.add(user)
            db.session.commit()
            flash('User registered successfully!')
            logging.info(f'User registered: {email}')
            return redirect(url_for('main.login'))
        except Exception as e:
            logging.error(f'Error during user registration: {str(e)}')
            flash('An error occurred during registration. Please try again.')
            return redirect(url_for('main.register'))

    return render_template('register.html')


@main.route('/profile/<int:user_id>', methods=['GET', 'POST'])
def profile(user_id):
    user = User.query.get_or_404(user_id)
    if request.method == 'POST':
        try:
            user.first_name = request.form['first_name']
            user.last_name = request.form['last_name']
            user.phone = request.form['phone']
            user.address = request.form['address']
            user.city = request.form['city']
            user.state = request.form['state']
            user.zip_code = request.form['zip_code']
            user.country = request.form['country']
            user.area = request.form['area']
            user.group = request.form['group']
            user.department = request.form['department']
            db.session.commit()
            flash('Profile updated successfully')
            logging.info(f'User updated profile: {user.email}')
            return redirect(url_for('main.profile', user_id=user.id))
        except Exception as e:
            logging.error(f'Error during profile update: {str(e)}')
            flash('An error occurred during profile update. Please try again.')
            return redirect(url_for('main.profile', user_id=user.id))
    return render_template('profile.html', user=user)


@main.route('/admin', methods=['GET'])
def admin():
    users = User.query.all()
    return render_template('admin.html', users=users)


@main.route('/admin/delete/<int:user_id>', methods=['POST'])
def delete_user(user_id):
    try:
        user = User.query.get_or_404(user_id)
        db.session.delete(user)
        db.session.commit()
        flash('User deleted successfully')
        logging.info(f'User deleted: {user.email}')
        return redirect(url_for('main.admin'))
    except Exception as e:
        logging.error(f'Error during user deletion: {str(e)}')
        flash('An error occurred during user deletion. Please try again.')
        return redirect(url_for('main.admin'))

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de personas</title>
    <link rel="stylesheet" href="/style/style.css">
</head>
    <body>
        <nav>
            <a href="register.html">Register</a>
            <a href="login.html">Login</a>
            <a href="admin.html">Admin</a>
        </nav>
            <h2>Admin - Manage Users</h2>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Area</th>
                        <th>Group</th>
                        <th>Department</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.area }}</td>
                        <td>{{ user.group }}</td>
                        <td>{{ user.department }}</td>
                        <td>
                            <form method="POST" action="{{ url_for('main.delete_user', user_id=user.id) }}">
                                <button type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>

                </tbody>
            </table>
    </body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de personas</title>
    <link rel="stylesheet" href="/style/style.css">
</head>
<body>
    <nav>
        <a href="register.html">Register</a>
        <a href="login.html">Login</a>
        <a href="admin.html">Admin</a>
    </nav>
    <div class="container">

                <ul class="flashes">
                    En esta pafina podras registrarte con las siguientes condiciones.
                    Desbes agregar:
                        <li>Nombre</li>
                        <li>Apellido</li>
                        <li>Correo electrónico</li>
                        <li>Número telefónico</li>
                        <li>Contraseña</li>
                </ul>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registro de personas</title>
        <link rel="stylesheet" href="/style/style.css">
    </head>
    <body>
        <nav>
            <a href="register.html">Register</a>
            <a href="layout.html">Inicio</a>
            <a href="admin.html">Admin</a>
        </nav>
        <h2>Login</h2>
        <form method="POST" action="{{ url_for('main.login') }}">
            <input type="email" name="email" placeholder="Email" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
    </body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de personas</title>
    <link rel="stylesheet" href="/style/style.css">
</head>
    <body>
        <nav>
            <a href="register.html">Register</a>
            <a href="login.html">Login</a>
            <a href="admin.html">Admin</a>
        </nav>
        <h2>Profile</h2>
        <form method="POST" action="{{ url_for('main.profile', user_id=user.id) }}">
            <input type="text" name="first_name" placeholder="First Name" value="{{ user.first_name }}" required>
            <input type="text" name="last_name" placeholder="Last Name" value="{{ user.last_name }}" required>
            <input type="text" name="address" placeholder="Address" value="{{ user.address }}">
            <input type="text" name="city" placeholder="City" value="{{ user.city }}">
            <input type="text" name="state" placeholder="State" value="{{ user.state }}">
            <input type="text" name="zip_code" placeholder="Zip Code" value="{{ user.zip_code }}">
            <input type="text" name="country" placeholder="Country" value="{{ user.country }}">
            <input type="text" name="area" placeholder="Area" value="{{ user.area }}">
            <input type="text" name="group" placeholder="Group" value="{{ user.group }}">
            <input type="text" name="department" placeholder="Department" value="{{ user.department }}">
            <button type="submit">Update Profile</button>
        </form>
    </body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de personas</title>
    <link rel="stylesheet" href="/style/style.css">
</head>
<body>
    <nav>
            <a href="layout.html">Inicio</a>
            <a href="login.html">Login</a>
            <a href="admin.html">Admin</a>
        </nav>
    <h2>Register</h2>
    <form method="POST" action="{{ url_for('main.register') }}">
        <input type="text" name="first_name" placeholder="First Name" required>
        <input type="text" name="last_name" placeholder="Last Name" required>
        <input type="email" name="email" placeholder="Email" required>
        <input type="phone" name="phone" placeholder="Phone number" required>
        <input type="password" name="password" placeholder="Password" required>
        <input type="text" name="address" placeholder="Address">
        <input type="text" name="city" placeholder="City">
        <input type="text" name="state" placeholder="State">
        <input type="text" name="zip_code" placeholder="Zip Code">
        <input type="text" name="country" placeholder="Country">
        <input type="text" name="area" placeholder="Area">
        <input type="text" name="group" placeholder="Group">
        <input type="text" name="department" placeholder="Department">
        <button type="submit">Register</button>
    </form>
</body>
</html>